alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias python='python3'
alias vi='lvim'
alias update='sudo apt update && sudo apt upgrade -y'
alias text='sudo systemctl isolate multi-user.target'
alias gui='sudo systemctl isolate graphical.target'
alias sd='shutdown -h now'
alias lastupdate='sudo awk -v RS="" "END {print}" /var/log/unattended-upgrades/unattended-upgrades-dpkg.log'
